
{
   "timers":[
      {
         "data":[
            {
               "ownMinTime":2,
               "ownTimeStdDev":13.152946437965905,
               "totalTimeStdDev":13.152946437965905,
               "ownTimeAvg":5,
               "ticks":357,
               "name":"coord_purge",
               "ownMaxTime":248,
               "totalMinTime":2,
               "totalMaxTime":248,
               "totalTimeAvg":5
            },
            {
               "ownMinTime":5,
               "ownTimeStdDev":27.440845468024488,
               "totalTimeStdDev":27.440845468024488,
               "ownTimeAvg":28,
               "ticks":4,
               "name":"job.info",
               "ownMaxTime":54,
               "totalMinTime":5,
               "totalMaxTime":54,
               "totalTimeAvg":28
            },
            {
               "ownMinTime":2,
               "ownTimeStdDev":13.674794331177344,
               "totalTimeStdDev":13.674794331177344,
               "ownTimeAvg":4,
               "ticks":357,
               "name":"purge",
               "ownMaxTime":262,
               "totalMinTime":2,
               "totalMaxTime":262,
               "totalTimeAvg":4
            }
         ],
         "group":"commands"
      },
      {
         "data":[
            {
               "ownMinTime":1,
               "ownTimeStdDev":8.0,
               "totalTimeStdDev":8.0,
               "ownTimeAvg":12,
               "ticks":9,
               "name":"v1admin",
               "ownMaxTime":29,
               "totalMinTime":1,
               "totalMaxTime":29,
               "totalTimeAvg":12
            },
            {
               "ownMinTime":0,
               "ownTimeStdDev":0.0,
               "totalTimeStdDev":34.92849839314596,
               "ownTimeAvg":0,
               "ticks":4,
               "name":"v1jobs",
               "ownMaxTime":2,
               "totalMinTime":6,
               "totalMaxTime":67,
               "totalTimeAvg":36
            },
            {
               "ownMinTime":2,
               "ownTimeStdDev":-1.0,
               "totalTimeStdDev":-1.0,
               "ownTimeAvg":2,
               "ticks":1,
               "name":"version-GET",
               "ownMaxTime":2,
               "totalMinTime":2,
               "totalMaxTime":2,
               "totalTimeAvg":2
            },
            {
               "ownMinTime":0,
               "ownTimeStdDev":0.0,
               "totalTimeStdDev":34.92849839314596,
               "ownTimeAvg":0,
               "ticks":4,
               "name":"v1jobs-GET",
               "ownMaxTime":2,
               "totalMinTime":6,
               "totalMaxTime":67,
               "totalTimeAvg":36
            },
            {
               "ownMinTime":1,
               "ownTimeStdDev":8.0,
               "totalTimeStdDev":8.0,
               "ownTimeAvg":12,
               "ticks":9,
               "name":"v1admin-GET",
               "ownMaxTime":29,
               "totalMinTime":1,
               "totalMaxTime":29,
               "totalTimeAvg":12
            },
            {
               "ownMinTime":2,
               "ownTimeStdDev":-1.0,
               "totalTimeStdDev":-1.0,
               "ownTimeAvg":2,
               "ticks":1,
               "name":"version",
               "ownMaxTime":2,
               "totalMinTime":2,
               "totalMaxTime":2,
               "totalTimeAvg":2
            }
         ],
         "group":"webservices"
      },
      {
         "data":[
            {
               "ownMinTime":0,
               "ownTimeStdDev":4.0,
               "totalTimeStdDev":4.0,
               "ownTimeAvg":5,
               "ticks":714,
               "name":"time.in.queue",
               "ownMaxTime":10,
               "totalMinTime":0,
               "totalMaxTime":10,
               "totalTimeAvg":5
            }
         ],
         "group":"callablequeue"
      },
      {
         "data":[
            {
               "ownMinTime":2,
               "ownTimeStdDev":12.727922061357855,
               "totalTimeStdDev":12.727922061357855,
               "ownTimeAvg":4,
               "ticks":354,
               "name":"coord-purge",
               "ownMaxTime":242,
               "totalMinTime":2,
               "totalMaxTime":242,
               "totalTimeAvg":4
            },
            {
               "ownMinTime":0,
               "ownTimeStdDev":0.0,
               "totalTimeStdDev":0.0,
               "ownTimeAvg":2,
               "ticks":21414,
               "name":"getRecoveryActionsGroupByJobId",
               "ownMaxTime":11,
               "totalMinTime":0,
               "totalMaxTime":11,
               "totalTimeAvg":2
            },
            {
               "ownMinTime":0,
               "ownTimeStdDev":0.0,
               "totalTimeStdDev":0.0,
               "ownTimeAvg":1,
               "ticks":25704,
               "name":"getWorkflowCountWithStatus",
               "ownMaxTime":72,
               "totalMinTime":0,
               "totalMaxTime":72,
               "totalTimeAvg":1
            },
            {
               "ownMinTime":1,
               "ownTimeStdDev":1.4142135623730951,
               "totalTimeStdDev":1.4142135623730951,
               "ownTimeAvg":2,
               "ticks":21414,
               "name":"getPendingActions",
               "ownMaxTime":215,
               "totalMinTime":1,
               "totalMaxTime":215,
               "totalTimeAvg":2
            },
            {
               "ownMinTime":0,
               "ownTimeStdDev":0.0,
               "totalTimeStdDev":0.0,
               "ownTimeAvg":1,
               "ticks":25704,
               "name":"getWorkflowCountWithStatusInLastNSecs",
               "ownMaxTime":7,
               "totalMinTime":0,
               "totalMaxTime":7,
               "totalTimeAvg":1
            },
            {
               "ownMinTime":3,
               "ownTimeStdDev":25.11971337416094,
               "totalTimeStdDev":25.11971337416094,
               "ownTimeAvg":18,
               "ticks":3,
               "name":"getWorkflowsInfo",
               "ownMaxTime":47,
               "totalMinTime":3,
               "totalMaxTime":47,
               "totalTimeAvg":18
            },
            {
               "ownMinTime":1,
               "ownTimeStdDev":0.0,
               "totalTimeStdDev":0.0,
               "ownTimeAvg":2,
               "ticks":42830,
               "name":"getRunningActionsOlderThan",
               "ownMaxTime":17,
               "totalMinTime":1,
               "totalMaxTime":17,
               "totalTimeAvg":2
            },
            {
               "ownMinTime":1,
               "ownTimeStdDev":4.242640687119285,
               "totalTimeStdDev":4.242640687119285,
               "ownTimeAvg":4,
               "ticks":4281,
               "name":"getCoordinatorJobsToBeMaterialized",
               "ownMaxTime":282,
               "totalMinTime":1,
               "totalMaxTime":282,
               "totalTimeAvg":4
            },
            {
               "ownMinTime":1,
               "ownTimeStdDev":1.7320508075688772,
               "totalTimeStdDev":1.7320508075688772,
               "ownTimeAvg":2,
               "ticks":21416,
               "name":"getRunningActions",
               "ownMaxTime":248,
               "totalMinTime":1,
               "totalMaxTime":248,
               "totalTimeAvg":2
            },
            {
               "ownMinTime":1,
               "ownTimeStdDev":1.4142135623730951,
               "totalTimeStdDev":1.4142135623730951,
               "ownTimeAvg":2,
               "ticks":21414,
               "name":"getCoordinatorJobsOlderThanStatus",
               "ownMaxTime":169,
               "totalMinTime":1,
               "totalMaxTime":169,
               "totalTimeAvg":2
            },
            {
               "ownMinTime":50,
               "ownTimeStdDev":-1.0,
               "totalTimeStdDev":-1.0,
               "ownTimeAvg":50,
               "ticks":1,
               "name":"getCoordinatorJobInfo",
               "ownMaxTime":50,
               "totalMinTime":50,
               "totalMaxTime":50,
               "totalTimeAvg":50
            },
            {
               "ownMinTime":1,
               "ownTimeStdDev":11.135528725660043,
               "totalTimeStdDev":11.135528725660043,
               "ownTimeAvg":2,
               "ticks":357,
               "name":"purge",
               "ownMaxTime":213,
               "totalMinTime":1,
               "totalMaxTime":213,
               "totalTimeAvg":2
            }
         ],
         "group":"db"
      }
   ],
   "samplers":[
      {
         "data":[
            {
               "name":"requests",
               "value":0.0
            },
            {
               "name":"v1admin",
               "value":0.0
            },
            {
               "name":"v0admin",
               "value":0.0
            },
            {
               "name":"v1jobs",
               "value":0.0
            },
            {
               "name":"v0jobs",
               "value":0.0
            },
            {
               "name":"callback",
               "value":0.0
            },
            {
               "name":"sla",
               "value":0.0
            },
            {
               "name":"v0job",
               "value":0.0
            },
            {
               "name":"v1job",
               "value":0.0
            },
            {
               "name":"version",
               "value":0.0
            }
         ],
         "group":"webservices"
      },
      {
         "data":[
            {
               "name":"connections.active",
               "value":6.0
            }
         ],
         "group":"jdbc"
      },
      {
         "data":[
            {
               "name":"threads.active",
               "value":0.0
            },
            {
               "name":"queue.size",
               "value":0.0
            }
         ],
         "group":"callablequeue"
      }
   ],
   "counters":[
      {
         "data":[
            {
               "name":"coord_purge",
               "value":357
            },
            {
               "name":"job.info",
               "value":4
            },
            {
               "name":"purge",
               "value":357
            }
         ],
         "group":"commands"
      },
      {
         "data":[
            {
               "name":"requests",
               "value":14
            },
            {
               "name":"v1admin",
               "value":9
            },
            {
               "name":"v1jobs",
               "value":4
            },
            {
               "name":"version-GET",
               "value":1
            },
            {
               "name":"v1jobs-GET",
               "value":4
            },
            {
               "name":"v1admin-GET",
               "value":9
            },
            {
               "name":"version",
               "value":1
            }
         ],
         "group":"webservices"
      },
      {
         "data":[
            {
               "name":"executed",
               "value":711
            },
            {
               "name":"queued",
               "value":714
            },
            {
               "name":"failed",
               "value":3
            }
         ],
         "group":"callablequeue"
      }
   ],
   "variables":[
      {
         "data":[
            {
               "name":"version",
               "value":"2.3.2-cdh3u5"
            }
         ],
         "group":"oozie"
      },
      {
         "data":[
            {
               "name":"from.classpath",
               "value":false
            },
            {
               "name":"log.over.web-service",
               "value":true
            },
            {
               "name":"config.file",
               "value":"oozie-log4j.properties"
            },
            {
               "name":"reload.interval",
               "value":10
            }
         ],
         "group":"logging"
      },
      {
         "data":[
            {
               "name":"config.file",
               "value":"\/etc\/oozie\/oozie-site.xml"
            },
            {
               "name":"config.dir",
               "value":"\/etc\/oozie"
            }
         ],
         "group":"configuration"
      },
      {
         "data":[
            {
               "name":"locks",
               "value":0
            }
         ],
         "group":"locks"
      },
      {
         "data":[
            {
               "name":"PREP",
               "value":0
            },
            {
               "name":"SUSPENDED",
               "value":0
            },
            {
               "name":"SUCCEEDED",
               "value":0
            },
            {
               "name":"RUNNING",
               "value":0
            },
            {
               "name":"FAILED",
               "value":0
            },
            {
               "name":"KILLED",
               "value":0
            }
         ],
         "group":"windowjobstatus"
      },
      {
         "data":[
            {
               "name":"PREP",
               "value":0
            },
            {
               "name":"SUSPENDED",
               "value":0
            },
            {
               "name":"SUCCEEDED",
               "value":0
            },
            {
               "name":"RUNNING",
               "value":0
            },
            {
               "name":"FAILED",
               "value":0
            },
            {
               "name":"KILLED",
               "value":0
            }
         ],
         "group":"jobstatus"
      },
      {
         "data":[
            {
               "name":"max.memory",
               "value":28556722176
            },
            {
               "name":"total.memory",
               "value":2058027008
            },
            {
               "name":"free.memory",
               "value":1914043728
            }
         ],
         "group":"jvm"
      }
   ]
}

